site_name: RDK Documentation
site_url: https://github.com/

repo_name: Source Code
repo_url: https://github.com/rdkcentral   

plugins:
  - search
  - mermaid2
use_directory_urls: true
theme:
  name: material
  logo: assets/logo.png
  custom_dir: overrides  
  favicon: assets/favicon.ico
  highlightjs: true
  user_color_mode_toggle: true
  features:
    - navigation.footer
    - navigation.tabs
    - toc.follow
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.tabs.link
    - content.tabs
    - content.width
    # - navigation.expand
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: '#00b2dc'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: '#00b2dc'
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  font:
    text: 'IBM Plex Sans'
    code: 'Fira Code'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_generator: "!!python/name:materialx.emoji.to_svg"
  - pymdownx.superfences: # Enable mermaid
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/entertainment.css
  - assets/stylesheets/getting-started.css
  - assets/stylesheets/connectivity.css
  - assets/stylesheets/devices.css
  - assets/stylesheets/footer.css
  - assets/stylesheets/sidepanes.css
  - assets/stylesheets/sitemap.css
  - assets/stylesheets/sample_home1.css
  - assets/stylesheets/sample_home2.css
  - assets/stylesheets/sample_home3.css
  - assets/stylesheets/sample_home4.css
  - assets/stylesheets/sample_home5.css
  - https://fonts.googleapis.com/icon?family=Material+Icons
extra_javascript:
  - assets/javascripts/extra.js
nav:
  - Home: README.md
  - Entertainment:
    - Home: ./entertainment/docs/README.md
    - sampleHome1: ./entertainment/docs/sample_home1.md
    - sampleHome2: ./entertainment/docs/sample_home2.md
    - Architecture: ./entertainment/docs/rdk7-architecture.md
    - Apps: ./entertainment/docs/Apps.md
    - Try Out RDK: ./entertainment/docs/tryout_rdkv_rdk7.md
    - Porting Kit: ./entertainment/docs/rdk7-vendor-porting-guide.md
    - Core Components:
      - Component List: ./entertainment/docs/rdkv_components.md
      - Westeros: ./entertainment/docs/components/westeros.md
      - RDK Shell: ./entertainment/docs/components/rdkshell.md
      - Rialto: ./entertainment/docs/components/rialto.md
    - Device Profiles: ./entertainment/docs/video_profiles.md
    - Releases: https://wiki.rdkcentral.com/display/RDK/RDK7+Release+Notes
  - Connectivity:
    - Home: ./connectivity/docs/README.md
    - Architecture: ./connectivity/docs/architecture.md
    - Features: ./connectivity/docs/features.md
    - Try Out RDK: ./connectivity/docs/tryout_rdkb.md
    - Device Profiles: ./connectivity/docs/profiles.md
    - Core Components:
      - Component List: ./connectivity/docs/rdkb_components.md
      - Cellular Manager: ./connectivity/docs/components/cellularmanager.md
      - WAN Manager: ./connectivity/docs/components/wanmanager.md
      - GPON Manager: ./connectivity/docs/components/gponmanager.md
      - PSM OldPrompt: ./connectivity/docs/components/PSM_Oldprompt.md
      - PSM GPT5: ./connectivity/docs/components/PSM_GPT5.md
      - PSM_Claude: ./connectivity/docs/components/PSM_Claude.md
      - WAN Mgr Rama: ./connectivity/docs/components/WANMgr Rama.md
      - WAN Mgr GPT5: ./connectivity/docs/components/WANMgr GPT5.md
    - Releases: https://wiki.rdkcentral.com/display/CMF/RDK-B+Code+Releases
  - Getting Started: ./preview-rdk/docs/getting-started.md
  - Devices: ./devices/docs/README.md
  - Tools:
      - TDK: ./tools/docs/TDK.md
      - Automatics: ./tools/docs/Automatics.md
  - Review:
      - Component List: ./review/README.md
      - WAN Manager: ./review/WANManager.md
      - Cellular Manager: ./review/CellularManager.md
      - GPON Manager: ./review/GPONManager.md
      - PPP Manager: ./review/PPPManager.md
      - VLAN Manager: ./review/VLANManager.md
      - Telco Voice Manager: ./review/TelcoVoiceManager.md
      - CCSP PSM: ./review/CCSPPSM.md
      - CCSP LM Lite: ./review/LMLite.md
      - CCSP PandM: ./review/CCSPPandM.md
      - One WiFi: ./review/OneWifi.md
      - RBus: ./review/RBus.md
      - Utopia: ./review/Utopia.md
  - Device Management:
      - Overview: ./device-management/docs/README.md
      - XConf: ./device-management/docs/XConf.md
      - Telemetry: ./device-management/docs/Telemetry.md
      - Web PA: ./device-management/docs/Webpa.md
      - TR 369: ./device-management/docs/TR369.md
      - Log Upload: ./device-management/docs/LogUpload.md
  - Comparison:
      - Template_Rama: ./docu/doc_template_orig_rama.md
      - Backup:
        - 26Sep: 
          - Claude:
            - PNM_Claude: ./docu/bhanu/pnm_claude.md
            - Utopia_Claude: ./docu/bhanu/utopia_claude.md
            - WANMGr_Claude: ./docu/bhanu/wanmgr_claude.md
            - Utopia_Claude: ./docu/bhanu/utopia_claude.md
            - CL_Claude: ./docu/raheen/cl_claude.md
            - LMLite_Claude: ./docu/raheen/lmlite_claude.md
            - PSM_Claude: ./docu/raheen/psm_claude.md
          - GPT5:
            - PNM_GPT5: ./docu/bhanu/pnm_gpt5.md
            - Utopia_GPT5: ./docu/bhanu/utopia_gpt5.md
            - WANMGr_GPT5: ./docu/bhanu/wanmgr_gpt5.md
            - Utopia_GPT5: ./docu/bhanu/utopia_gpt5.md
            - CL_GPT5: ./docu/raheen/cl_gpt5.md
            - LMLite_GPT5: ./docu/raheen/lmlite_gpt5.md
            - PSM_GPT5: ./docu/raheen/psm_gpt5.md
        - 30Sep:
          - Template_2609: ./docu/doc_template_mod_2609.md
          - Claude:
            - WANMGr_Claude_2609: ./docu/sep26/WANMgr_Claude_2609.md
            - LMLite_Claude_2609: ./docu/sep26/LMLite_Claude_2609.md
            - PSM_Claude_2609: ./docu/sep26/PSM_Claude_2609.md
            - RBUS_Claude_2609: ./docu/sep26/RBUS_Claude_2609.md
          - GPT5:
            - WANMGr_GPT5_2609: ./docu/sep26/WANMgr_GPT5_2609.md
            - LMLite_GPT5_2609: ./docu/sep26/LMLite_GPT5_2609.md
            - PSM_GPT5_2609: ./docu/sep26/PSM_GPT5_2609.md
            - RBUS_GPT5_2609: ./docu/sep26/RBUS_GPT5_2609.md
        - Oct10:
          - WAN Manager: ./docu/templateOct10/wanmanager.md
          - GPON Manager: ./docu/templateOct10/gponmanager.md
          - One WiFi: ./docu/templateOct10/onewifi.md
        - Oct21:
          - WAN Manager: ./docu/oct21/wanmanager.md
          - GPON Manager: ./docu/oct21/gponmanager.md
          - One WiFi: ./docu/oct21/onewifi.md
        - Oct22:
          - Template: ./docu/oct22/doc_template_22.md
          - WAN Manager: ./docu/oct22/wanmanager.md
          - GPON Manager: ./docu/oct22/gponmanager.md
          - LMLite: ./docu/oct22/lmlite.md
        - Oct27:
          - Template: ./docu/oct22/doc_template_22.md
          - WAN Manager: ./docu/oct27/wanmanager.md
          - GPON Manager: ./docu/oct27/gponmanager.md
          - CCSP PSM: ./docu/oct27/ccsppsm.md
          - RBUS: ./docu/oct27/rbus.md
          - Utopia: ./docu/oct27/utopia.md
        - Oct28:
          - WAN Manager: ./docu/oct28/wanmanager.md
          - GPON Manager: ./docu/oct28/gponmanager.md
          - One WiFi: ./docu/oct28/onewifi.md
          - CCSP LMLite: ./docu/oct28/ccsplmlite.md
          - GPON Manager: ./docu/oct28/gponmanager.md
          - One WiFi: ./docu/oct28/onewifi.md
          - CCSP LMLite: ./docu/oct28/ccsplmlite.md
          - GPON Manager: ./docu/oct28/gponmanager.md
          - One WiFi: ./docu/oct28/onewifi.md
          - CCSP LMLite: ./docu/oct28/ccsplmlite.md
          - GPON Manager: ./docu/oct28/gponmanager.md
          - One WiFi: ./docu/oct28/onewifi.md
          - CCSP LMLite: ./docu/oct28/ccsplmlite.md
        - Chunked:
          - CCSP PNM:
            - Overview: ./docu/chunked/pnm/Overview.md
            - Design: ./docu/chunked/pnm/Design.md
            - Interactions: ./docu/chunked/pnm/Interactions.md
          - WAN Manager:
            - Overview: ./docu/chunked/wanmanager/Overview.md
            - Design: ./docu/chunked/wanmanager/Design.md
            - Interactions: ./docu/chunked/wanmanager/Interactions.md
          - LMLite:
            - Overview: ./docu/chunked/lanmanager/Overview.md
            - Design: ./docu/chunked/lanmanager/Design.md
            - Interactions: ./docu/chunked/lanmanager/Interactions.md            
          - Utopia:
            - Overview: ./docu/chunked/utopia/Overview.md
            - Design: ./docu/chunked/utopia/Design.md
            - Interactions: ./docu/chunked/utopia/Interactions.md          
        - Dec02:
          - TestnDiagnostics: ./docu/dec02/tnd.md
          - CcspCR: ./docu/dec02/ccspcr.md
          - FAQ: ./docu/dec02/faq.md
      - Oct29:
        - WAN Manager: ./docu/oct29/wanmanager.md
        - GPON Manager: ./docu/oct29/gponmanager.md
        - VLAN Manager: ./docu/oct29/vlanmanager.md
        - One WiFi: ./docu/oct29/onewifi.md
        - CCSP LMLite: ./docu/oct29/ccsplmlite.md
        - CCSP PSM: ./docu/oct29/ccsppsm.md
        - CCSP PNM: ./docu/oct29/ccsppnm.md
        - CCSP CM Agent: ./docu/oct29/ccspcmagent.md
        - RBUS: ./docu/oct29/rbus.md
        - Utopia: ./docu/oct29/utopia.md
      - Oct31:
        - WAN Manager: ./docu/oct31/wanmanager.md
        - CCSP LMLite: ./docu/oct31/ccsplmlite.md
        - Utopia: ./docu/oct31/utopia.md
        - GPON Manager: ./docu/oct31/gponmanager.md
      - Nov04:
        - WAN Manager: ./docu/nov04/wanmanager.md
        - CCSP LMLite: ./docu/nov04/ccsplmlite.md
        - Utopia: ./docu/nov04/utopia.md
        - GPON Manager: ./docu/nov04/gponmanager.md
        - CCSP CM Agent: ./docu/nov04/ccspcmagent.md
        - CCSP Common Lib: ./docu/nov04/ccspcommonlibrary.md
        - CCSP DMCLI: ./docu/nov04/ccspdmcli.md
        - CCSP PSM: ./docu/nov04/ccsppsm.md
        - CCSP PNM: ./docu/nov04/ccsppnm.md
        - CCSP TR69PA: ./docu/nov04/ccsptr69pa.md
        - CCSP WiFiAgent: ./docu/nov04/ccspwifiagent.md
        - Cellular Manager: ./docu/nov04/cellularmanager.md
        - GW ProvApp: ./docu/nov04/gwprovapp.md
        - GW ProvApp EPON: ./docu/nov04/gwprovapp_epon.md
        - One WiFi: ./docu/nov04/onewifi.md
        - PPP Manager: ./docu/nov04/pppmanager.md
        - RBUS: ./docu/nov04/rbus.md
        - Telco Voice Manager: ./docu/nov04/telcovoicemanager.md
        - VLAN Manager: ./docu/nov04/vlanmanager.md
      - Nov05:
        - Component List: ./docu/nov05/rdkb_components.md
        - WAN Manager: ./docu/nov05/wanmanager.md
        - CCSP LMLite: ./docu/nov05/ccsplmlite.md
        - Utopia: ./docu/nov05/utopia.md
        - GPON Manager: ./docu/nov05/gponmanager.md
        - CCSP CM Agent: ./docu/nov05/ccspcmagent.md
        - CCSP Common Lib: ./docu/nov05/ccspcommonlibrary.md
        - CCSP DMCLI: ./docu/nov05/ccspdmcli.md
        - CCSP PSM: ./docu/nov05/ccsppsm.md
        - CCSP PNM: ./docu/nov05/ccsppnm.md
        - CCSP TR69PA: ./docu/nov05/ccsptr69pa.md
        - CCSP WiFiAgent: ./docu/nov05/ccspwifiagent.md
        - Cellular Manager: ./docu/nov05/cellularmanager.md
        - GW ProvApp: ./docu/nov05/gwprovapp.md
        - GW ProvApp EPON: ./docu/nov05/gwprovapp_epon.md
        - One WiFi: ./docu/nov05/onewifi.md
        - PPP Manager: ./docu/nov05/pppmanager.md
        - RBUS: ./docu/nov05/rbus.md
        - Telco Voice Manager: ./docu/nov05/telcovoicemanager.md
        - VLAN Manager: ./docu/nov05/vlanmanager.md
        
